-- tb_user
INSERT INTO tb_user (id, name, email, password, cpf, birthday, genero, favorite_language, account_type, status, created_at, updated_at) VALUES
                                                                                                                                            (1, 'Alice Silva', 'alice@email.com', 'senha123', '12345678901', '2000-05-10', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (2, 'Bruno Costa', 'bruno@email.com', 'senha123', '23456789012', '1999-03-22', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (3, 'Carla Souza', 'carla@email.com', 'senha123', '34567890123', '2001-07-18', 'FEMALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (4, 'Daniel Oliveira', 'daniel@email.com', 'senha123', '45678901234', '2000-12-05', 'MALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (5, 'Eduarda Lima', 'eduarda@email.com', 'senha123', '56789012345', '1998-11-30', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (6, 'Fábio Martins', 'fabio@email.com', 'senha123', '67890123456', '2002-01-15', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (7, 'Gabriela Rocha', 'gabriela@email.com', 'senha123', '78901234567', '2001-04-20', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (8, 'Hugo Pereira', 'hugo@email.com', 'senha123', '89012345678', '1999-09-02', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (9, 'Isabela Ramos', 'isabela@email.com', 'senha123', '90123456789', '2000-06-12', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (10, 'João Fernandes', 'joao@email.com', 'senha123', '01234567890', '2002-02-28', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (11, 'Karen Gomes', 'karen@email.com', 'senha123', '11234567890', '2001-08-14', 'FEMALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (12, 'Lucas Almeida', 'lucas@email.com', 'senha123', '21234567890', '2000-10-07', 'MALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (13, 'Mariana Castro', 'mariana@email.com', 'senha123', '31234567890', '1999-01-25', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (14, 'Nicolas Pinto', 'nicolas@email.com', 'senha123', '41234567890', '2002-03-30', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (15, 'Olívia Dias', 'olivia@email.com', 'senha123', '51234567890', '2001-12-11', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (16, 'Pedro Moreira', 'pedro@email.com', 'senha123', '61234567890', '2000-07-09', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (17, 'Quésia Rocha', 'quesia@email.com', 'senha123', '71234567890', '1998-05-27', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (18, 'Rafael Cardoso', 'rafael@email.com', 'senha123', '81234567890', '1999-11-03', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (19, 'Sofia Nunes', 'sofia@email.com', 'senha123', '91234567890', '2002-08-21', 'FEMALE', 'PORTUGUESE', 'STUDENT', 'ACTIVE', NOW(), NOW()),
                                                                                                                                            (20, 'Thiago Azevedo', 'thiago@email.com', 'senha123', '10234567890', '2000-09-15', 'MALE', 'ENGLISH', 'STUDENT', 'ACTIVE', NOW(), NOW());

-- student
INSERT INTO student (id, total_score, nivel) VALUES
                                                 (1, 1500, 3),
                                                 (2, 1200, 2),
                                                 (3, 1800, 4),
                                                 (4, 1100, 1),
                                                 (5, 2000, 5),
                                                 (6, 900, 1),
                                                 (7, 1700, 4),
                                                 (8, 1300, 2),
                                                 (9, 1600, 3),
                                                 (10, 1400, 3),
                                                 (11, 1500, 3),
                                                 (12, 1250, 2),
                                                 (13, 1900, 5),
                                                 (14, 1150, 1),
                                                 (15, 1750, 4),
                                                 (16, 1350, 2),
                                                 (17, 2000, 5),
                                                 (18, 1100, 1),
                                                 (19, 1550, 3),
                                                 (20, 1450, 3);